---
repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'  # Use the sha / tag you want to point at
    hooks:
      - id: yapf
        exclude: tests/gcodes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: tests/gcodes
      - id: end-of-file-fixer
        exclude: tests/gcodes
      - id: trailing-whitespace
        exclude: tests/gcodes
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #  rev: v2.4.4
  #  hooks:
  #    - id: pylint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: tests/gcodes
