---
repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'  # Use the sha / tag you want to point at
    hooks:
      - id: yapf
        exclude: tests/gcodes
        additional_dependencies: ['toml']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: tests/gcodes
      - id: end-of-file-fixer
        exclude: tests/gcodes
      - id: trailing-whitespace
        exclude: tests/gcodes
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: tests/gcodes
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.280'
    hooks:
    - id: ruff
