name: Rebase Pull Requests
on:
  push:
    branches: '**'
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - name: Automatic Rebase
      # You may pin to the exact commit or the version.
      # uses: cirrus-actions/rebase@cf2ad5908b365d40882ef06dab959717ec1aaf71
      uses: cirrus-actions/rebase@1.2
